### ISSUE TITLE
Inconsistency in # of users affected

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.UI#103]
Because user totals are cached, it's possible that the total number of users isn't consistent with the number of users affected. This is most visible with session start events, because they usually affect exactly 100% of all users. In this case we see percentages that exceed 100%

**Comment by niemyjski** [comment]
I need to add a setting to cap it at 100%, users are cached for a short while and this is why you are seeing this.

**Comment by niemyjski** [comment]
https://github.com/exceptionless/ng-filters/commit/5f9c3d513fd3fa75899690f3ce036fa5547316a5
