### ISSUE TITLE
Inconsistency in session duration

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.UI#104]
In Reports -> Sessions we see sessions that are for example Created: 3 minutes ago with Duration: 4 minutes. This could give the impression that the data behind this is inconsistent, but it's probably just due to them updating out of sync.

**Comment by niemyjski** [comment]
We need to shorten the interval of the date updates from 1 minute to 10 seconds or 15 seconds and maybe set the interval to renew exactly on the minute change so it updates in real time :)
