### ISSUE TITLE
Add column for 'Project' to the Dashboard tables

### ISSUE THREAD

**Issue by jdtaylor91** [exceptionless/Exceptionless.UI#107]
When viewing exceptions with the 'All Projects' selector selected it is not obvious as to which project each exception relates to.

Would it be possible to add an additional column to the 'Most Frequent' and 'Most Recent' tables on the Exceptions Dashboard to display the Project name when 'All Projects' is selected?

**Comment by niemyjski** [comment]
We want to add a tag for the project name as shown in this issue: https://github.com/exceptionless/Exceptionless.UI/issues/10 Would this be better than a column?

**Comment by jdtaylor91** [comment]
Thanks for the quick response - yeah that would be perfect, sorry i must have missed that issue.

Do you have a timescale on when you think that will be released by?

**Comment by niemyjski** [comment]
I don't, I was thinking over the weekend that we need to update a general timeline of what we are thinking of on the main repo.
 * We've been racing towards finishing up a major refactor to the underlying code so we can upgrade to elastic search 2.x &5/x much easier and enable better aggregation results (which we found we needed support for complex aggregations (TLDR: So we can make rich custom dashboards that are not numeric based while returning results much faster).
* Overall our focus has been we need additional / improved dashboards & better/smarter notifications.

With all of this said I'll try to squeeze #10 in the next release but if you wanted to submit a pr for this it would be a huge help :). We get any substantial pr a free year of the small plan and all the credit :).

**Comment by niemyjski** [comment]
Also, please feel free to join our slack: https://slack.exceptionless.com/ and give us heck about these kind of issues.

**Comment by jdtaylor91** [comment]
Thanks, would be great if it could be included in the next release, i understand you have more pressing work to get done before that though!

Unfortunately i'm not too familiar with angular so i'm not in a position to submit a pull request for the change.

**Comment by niemyjski** [comment]
We'll be adding a column for this in the very near future (after we push the server side updates sometime this/next week).

**Comment by jdtaylor91** [comment]
Brilliant, thanks for the update!
