### ISSUE TITLE
Mark Fixed does not accept a version number with four values

### ISSUE THREAD

**Issue by andersgenberg** [exceptionless/Exceptionless.UI#108]
In the Stacking view, when clicking "Mark Fixed" a dialog appears where you can enter the version number of the fix. But you cannot enter a standard windows four-digit version number. 

https://github.com/exceptionless/Exceptionless/wiki/Versioning

**Comment by niemyjski** [comment]
I just added a new section to the wiki: https://github.com/exceptionless/Exceptionless/wiki/Versioning/_compare/fb45f78b6a772a464eeae02ef39957dff4e95e03...23a4e89b1211ee2511a6f89ff4c8d24ed68ea9f7

> **NOTE:** If you are using a **four-part version number** (E.G., `1.2.3.4`), you'll need to enter it as `1.2.3-4`. We will automatically handle this conversion when processing events.

I Hope this helps. If you have any feedback on how we can make this better please leave a comment!
