### ISSUE TITLE
Unable to 'Mark Fixed' a Broken Link from the stack page

### ISSUE THREAD

**Issue by jdtaylor91** [exceptionless/Exceptionless.UI#111]
The 'Mark Fixed' button is not visible on the stack page for an exception that appears in the Broken Links section.

The only way to 'Mark Fixed' is then to use the 'Bulk Action' action on the Dashboard to set them as fixed, could the 'Mark Fixed' button be included against Broken Links as it is against normal Exceptions?

Screenshots to demo
Missing 'Mark Fixed' button
![example1](https://cloud.githubusercontent.com/assets/12166669/18989339/5a6678e0-8703-11e6-87d2-60728c1a47db.png)

Bulk Action
![example2](https://cloud.githubusercontent.com/assets/12166669/18989347/65e496b6-8703-11e6-86e2-056e9bb3d740.png)

**Comment by niemyjski** [comment]
I didn't consider this, thanks for pointing out, we moved it to only appear on error stacks but it should also be on 404 stacks. I'll get this fixed.

**Comment by niemyjski** [comment]
This will be auto deployed after the build completes. Thanks for letting us know about this.

**Comment by jdtaylor91** [comment]
Thanks for the quick response and fix.
