### ISSUE TITLE
Could the currently selected page be expanded in the left hand navigation menu?

### ISSUE THREAD

**Issue by jdtaylor91** [exceptionless/Exceptionless.UI#114]
When viewing a dashboard it is not obvious as to which page you are viewing if the navigation menu on the left is collapsed, could the currently selected page always be expanded so this is less confusing?

E.g. When collapsed i have no way of knowing what page this is without inspecting the page URL:
![example1](https://cloud.githubusercontent.com/assets/12166669/19304635/696ea5a4-9065-11e6-9c87-3d76fed3b339.png)

This would benefit from the menu being always open for the currently selected page, it is then immediately clear as to which page you are viewing:
![example2](https://cloud.githubusercontent.com/assets/12166669/19304642/6d352f3c-9065-11e6-93bd-be637f4b5514.png)

**Comment by jdtaylor91** [comment]
Alternatively the currently selected menu item could be highlighted i.e.

![example3](https://cloud.githubusercontent.com/assets/12166669/19304739/d7f4a122-9065-11e6-99dd-e0b63d85b2b5.png)

**Comment by ejsmith** [comment]
I agree. We should expand the current node in the menu.

**Comment by niemyjski** [comment]
@jdtaylor91 what route are you hitting that makes it so it's not expanded. Could you give me the steps you need to take.

**Comment by jdtaylor91** [comment]
This happens when first logging in, it goes to #/type/error/dashboard and the no menu items are expanded or selected.

It also happens when going directly to a page by using a link/shortcut instead of navigating to the page by using the menu.

**Comment by niemyjski** [comment]
Thanks for the heads up, I'll take a look into this and we'll get this fixed. Just curious what browser are you using?

**Comment by jdtaylor91** [comment]
Chrome latest version - v54.0.2840

**Comment by niemyjski** [comment]
This has been fixed along with perf issues caused by the menu's + data binding
