### ISSUE TITLE
No line breaks in multi-line text in extended data

### ISSUE THREAD

**Issue by andersgenberg** [exceptionless/Exceptionless.UI#116]
1. Add multi-line text to extended data of an exception.
2. Press the button "Toggle View"

The text is displayed within a pre-tag, but all the line breaks are removed.

**Comment by niemyjski** [comment]
Do you have a link to the event or raw text you are seeing this with? I think it could be the plugin we are using for multiline rendering.

**Comment by andersgenberg** [comment]
Here is a link to an exception with this problem:
https://be.exceptionless.io/event/5821746bd58ba236d4d04558

Switch to the tab "Extended Data" and there is a property "Extra Text" with what should be three lines of text.
If you press the button "Toggle Veiw" you can se \r\n instead of the line breaks.

**Comment by niemyjski** [comment]
Yeah, I wonder why it's not being rendered. I'll take a look into it: `"Line1\r\nLine2\r\nLine3"`

**Comment by andersgenberg** [comment]
👍

**Comment by jconway45** [comment]
Any update on this? I am trying to render similar output "Line1\r\nLine2\r\nLine3" to the Message value on an info log and it's not displaying the line breaks,

**Comment by niemyjski** [comment]
I haven't had a chance to take a look into this, I've been focusing on converting the backend to Elasticsearch 5 the past 2 months and getting really close but more work to do. I'll be back on the UI after the server api is done so I can work on the ui.

Is there any chance you could take a look into this in the mean time?

**Comment by caesay** [comment]
@niemyjski does #125 close this? is #129 a different issue?

**Comment by niemyjski** [comment]
@caesay it doesn't appear so:

`"Line1\r\nLine2\r\nLine3"`

![screen shot 2017-04-11 at 10 18 08 am](https://cloud.githubusercontent.com/assets/1020579/24916591/314d78ca-1ea0-11e7-8f29-d1da52d9d6b5.png)

**Comment by andersgenberg** [comment]
It is solved, I think.
![image](https://cloud.githubusercontent.com/assets/19546404/24961470/2b7ad66e-1f99-11e7-9fb6-caa24ec52075.png)

**Comment by niemyjski** [comment]
I kinda think the raw json view is showing correctly, you want to see what kind of line breaks there are in the raw json. If we can all agree on this lets close this issue.

**Comment by andersgenberg** [comment]
Agree!
