### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by barankaynak** [exceptionless/Exceptionless.UI#117]
In the administration panel there should be a user management page. Administrators cant add users or update them. Admin can only add/remove user from organisation. Also a role managemnt interface is missing.

**Comment by niemyjski** [comment]
We currently only have the ability to manage users on the organization level and have no concept of user roles except for (user and global admin). We want to add this to the global admin section as we had in 1.x but we've been working on other things :\. but there are currently higher priorities like elastic 5, notification improvements and custom dashboards. We'll get this eventually, it's just a matter of priorities. If you are interested in starting a discussion and implementing this please let us know. In the mean time I'm going to close this to help keep the issues maintainable and reopen when we revisit.
