### ISSUE TITLE
Custom time filter does not work

### ISSUE THREAD

**Issue by Naggorny** [exceptionless/Exceptionless.UI#12]
1.Open filter
2.Set today dates
3 Click on Apply 

AR: nothing happens
ER: exceptions for custom dates should be displayed 
![2015-03-18_170238](https://cloud.githubusercontent.com/assets/11498834/6711645/e99d48dc-cd90-11e4-9e60-8d05937f1ab8.jpg)

**Comment by niemyjski** [comment]
This is a known bug where setting the start and end to the same day doesn't work. I'll make sure this is fixed soon. Also, we are working on moving all of our trello cards over time to github.

**Comment by niemyjski** [comment]
In the mean time, I'd use the last 24 hours date filter as a work around.

**Comment by Naggorny** [comment]
Trello is the great App

**Comment by niemyjski** [comment]
It's great, but it doesn't really allow the community to see what we are working on (we can't show some sensitive stuff) but we can be a lot more transparent.

**Comment by niemyjski** [comment]
This is now what it looks like.
![image](https://cloud.githubusercontent.com/assets/1020579/6910944/d3adb6d6-d71f-11e4-8239-964c7a255a89.png)

**Comment by niemyjski** [comment]
These changes have been deployed to production. Please let us know if you have any questions.

**Comment by ejsmith** [comment]
Shouldn't you just show that dialog when they click custom vs showing the select date range dialog 1st? Why do we need to show that?

**Comment by niemyjski** [comment]
because the other method allows you to use your keyboard.

**Comment by ejsmith** [comment]
That is a silly reason to show both. They are both very similar dialogs. To me it makes no sense to use both. And I'm sure you can use your keyboard in the new dialog as well.

**Comment by Naggorny** [comment]
Hi guys.
One question:
- is there any case to have ability to set range like from 03.31.2015 10:00 until now in custom time filter? This functionality is very important for me.

**Comment by niemyjski** [comment]
Currently no, but this is something that needs to be tweaked. Will you create a new issue for this.

**Comment by Naggorny** [comment]
Issue-19 ( https://github.com/exceptionless/Exceptionless.UI/issues/19 ) has been created

**Comment by niemyjski** [comment]
Thanks
