### ISSUE TITLE
Typo on client configuration tab when editing a project

### ISSUE THREAD

**Issue by sacarino** [exceptionless/Exceptionless.UI#128]
`redploying` => `redeploying` 

[Line is here](https://github.com/exceptionless/Exceptionless.UI/blob/1f3fcfb5ed60a72f832d031c0ce4eb7a68bc1179/src/app/project/manage/tabs/client-configuration.tpl.html#L3)

**Comment by niemyjski** [comment]
Thanks for logging this, we really appreciate it. I've fixed this in the referencing commit!
