### ISSUE TITLE
On stack page, don't hide occurrences when stack is marked 'fixed'

### ISSUE THREAD

**Issue by BillHenning** [exceptionless/Exceptionless.UI#13]
When I was fixing an exception and visiting its stack page, I noticed that as soon as I clicked the Mark Fixed button, all of the occurrences in the list below disappeared.  This is because the filter at the top of the page header doesn't have marked to include fixed.  I think this behavior is wrong though.

When I'm on a stack page, I want to see the occurrences for that stack, even if the stack has been fixed.  I don't think the page header filter should affect that list.  I do think the filter is a useful feature for the main dashboards though.

**Comment by niemyjski** [comment]
But what if you have a stack of log messages with no source defined. You would want to search by log content.

**Comment by BillHenning** [comment]
I'm not sure what the right answer is, but I can say the scenario I ran into just doesn't feel right.  Without knowing better, I'm not sure I would have thought to even look at the filter for why the items didn't show in the list.  It's not super discoverable for that.  I may have assumed it was only for the main dash pages.

I would possibly suggest making that filter UI more apparent for the list or if not, perhaps showing some message by the list saying it's currently filtering by 'xxx' so that people know and have a link that opens the filter popup at the top.

**Comment by niemyjski** [comment]
:+1: Any ideas on how you'd update the stack page to put the filtering message? This might be useful across the rest of the site as well

**Comment by BillHenning** [comment]
Maybe on the right side of the header (like in the same box as Recent Occurrences), have a link that says "X events are hidden per your filter settings", and the link would open the filter settings.  

But honestly I think it sort of sucks to have to constantly switch that on/off to view them on the detail page because back on the dashboard, I don't want to see fixed stacks.

**Comment by niemyjski** [comment]
Yeah, that does suck

**Comment by niemyjski** [comment]
@ejsmith and I talked about this the other day when we were working on session views and we decided to keep it as it is as it's by design. We did however, update the grid text to say something when you are filtering.
