### ISSUE TITLE
Add button for keyboard shortcuts

### ISSUE THREAD

**Issue by TheSaltyKorean** [exceptionless/Exceptionless.UI#136]
Never knew the keyboard shortcuts existed until some Wisconsonite showed me.  Put a link somewhere on the page so we know what they are.

**Comment by caesay** [comment]
+1 for a keyboard shortcut help page. @niemyjski can we just put a page in the wiki for now? I don't know what the shortcuts are either or I would do it.

**Comment by niemyjski** [comment]
You just need to press `?` on any page to see what the shortcuts are. They change from page to page and we need to find a good way to let users know about it.

**Comment by niemyjski** [comment]
I added a help tip to bottom of the wiki!
