### ISSUE TITLE
A double-quoted search value breaks page navigation in the recent view

### ISSUE THREAD

**Issue by rstarkov** [exceptionless/Exceptionless.UI#139]
If I search for `tags:xyz` and have several pages' worth of results, paging works as expected. But if I search for `tags:"xyz"`, the search results are the same, but paging is broken. I can go to page 2, and at this point it breaks: attempting to go to page 3 goes back to page 1 instead, while showing "21-40" at the bottom of the list. Paging controls stop working altogether at this point.

**Comment by niemyjski** [comment]
Thanks for bringing this to our attention, I'll take a look into this and get this resolved.

**Comment by rstarkov** [comment]
Just noticed that when it breaks, the browser network log shows a request that 404's due to a malformed URL.

Good URL:

> /api/v2/projects/[...]/events?filter=project:[...]+type:log+fixed:false+hidden:false+(tags:test)&limit=20&mode=summary&offset=60m

Go a few pages forward, bad URL:

> /api/v2/projects/[...]/events?filter=project:[...]+type:log+fixed:false+hidden:false+(tags:test)&limit=20&limit=20&limit=20,20&limit=20,20,20,20&limit=20,20,20,20,20,20,20,20&limit=20,20,20,20,20,20,20,20,20,20,20,20,20,20,20,20&mode=summary&mode=summary&mode=summary,summary&mode=summary,summary,summary,summary&mode=summary,summary,summary,summary,summary,summary,summary,summary&mode=summary,summary,summary,summary,summary,summary,summary,summary,summary,summary,summary,summary,summary,summary,summary,summary&offset=60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test)&offset=60m&offset=60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m&offset=60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m&offset=60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m&offset=60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m,60m%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test),60m&page=2%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test)&page=3%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test)&page=2%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test)&page=2%3Ffilter%3Dproject:[...]+type:log+fixed:false+hidden:false+(tags:test)&page=2

**Comment by niemyjski** [comment]
That's not good, I'll take a look at this very soon, it's on my list for the current sprint, just finishing up some other work.

**Comment by niemyjski** [comment]
I'm closing this as I'm merging this into https://github.com/exceptionless/Exceptionless/issues/332
