### ISSUE TITLE
There is no way to combine wildcards and queries that need quoting

### ISSUE THREAD

**Issue by rstarkov** [exceptionless/Exceptionless.UI#140]
For example, suppose I want to search for `path:"/xyz/*"` or `machine:"eu-prod*"`. `/` and `-` require the quotes, but quotes also interpret `*` literally.

**Comment by niemyjski** [comment]
I believe you need to escape them with `\` (https://github.com/exceptionless/Foundatio.Parsers/blob/74af1768429ab13e1698068d58c358411b5a9b7f/tests/Foundatio.Parsers.LuceneQueries.Tests/StringExtensionsTests.cs) Can you please try this and let me know

**Comment by rstarkov** [comment]
It looks like `\` is the correct way to escape special characters as per [Lucene docs](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html) but it doesn't seem to work in Exceptionless: searching for `machine:eu\-prod*` results in "An invalid search term was found".

**Comment by niemyjski** [comment]
Thanks, I'lll take a look into this hopefully by the end of the week, are you currently blocked on this?. I'm working on slack support and pretty close to completing a first pass then I'll look into this and the other issue you ran into.

**Comment by rstarkov** [comment]
So far I was always able to find some alternative way of searching for what I needed, so it's not particularly urgent at the moment. Thanks!

**Comment by niemyjski** [comment]
I'm closing this as I'm merging this into https://github.com/exceptionless/Exceptionless/issues/332
