### ISSUE TITLE
Move projects between organizations

### ISSUE THREAD

**Issue by caesay** [exceptionless/Exceptionless.UI#141]
When managing many organizations it is a frequent thing that you may need to move a project from one organization to another, and it would be good if you could keep the history and api keys the same while doing so.

I'm not sure what considerations there should be for security etc, perhaps only the project creator/owner can move it to a different organization?

**Comment by niemyjski** [comment]
Yeah, I'm not sure how this would work but a lot of stuff would need to be batch updated like tokens, projects, stacks, events and I'm probably missing something else. We have no concept of owners so this could be a problem, the first step probably would be to add an admin end point and a job that moves this. One of the problems of having this is we don't have the concept of transactions so you'd better hope that it didn't fail half way through. It might also cause massive io in the elastic cluster.

**Comment by niemyjski** [comment]
Also, what about things that might in the cache under a scoped key. It's worth looking into this but we gotta be careful about it.

**Comment by niemyjski** [comment]
Would you be willing to take a look into this?

**Comment by niemyjski** [comment]
I'm going to close this because we don't get asked todo this much. We'd be willing to talk about this more in depth if someone would be willing to submit a pr.
