### ISSUE TITLE
Add sort indicator to time column in event list grid.

### ISSUE THREAD

**Issue by edwardmeng** [exceptionless/Exceptionless.UI#144]
After investigating the backend apis, the sort parameter has been provided. But the sorting function does not implemented on the UI to the end users. And now we just want to sort the events ascending by time.

**Comment by niemyjski** [comment]
We'd be willing to accept a pr for this behavior. This is something we'd like to have as well.

**Comment by edwardmeng** [comment]
Would you want me to implement it and send the pull request? Or you have other plans to implement this feature.

**Comment by laughinggoose** [comment]
#146 addressed this, so I believe it should be okay to close @niemyjski

**Comment by niemyjski** [comment]
Thanks again!
