### ISSUE TITLE
Redundant &nbsp; in extended tab leads incorrect layout of 'Toggle View' button

### ISSUE THREAD

**Issue by edwardmeng** [exceptionless/Exceptionless.UI#149]
In the extended tab of the event details view, the 'Toggle View' layouts incorrectly in Chrome 60.0 as following:
![qq 20170812185936](https://user-images.githubusercontent.com/2819989/29240074-85591496-7f90-11e7-903b-5cf4752cfcef.png)
And the rendered html will be:
```html
<div class="btn-group btn-group-xs">
    <button type="button" role="button" class="btn btn-dark btn-xs" ng-click="vm.showRaw = !vm.showRaw">Toggle View</button>
    &nbsp; 
    <!---->
    <button type="button" role="button" class="btn btn-dark btn-xs dropdown-toggle" data-toggle="dropdown" ng-if="vm.canPromote"> 
        <span class="caret"></span> 
    </button>
    <!----> 
    <!---->
    <ul class="dropdown-menu pull-right" ng-if="vm.canPromote"> 
        <!---->
        <li ng-if="!vm.isPromoted">
            <a ng-click="vm.promoteTab()">Promote to Tab</a>
        </li>
        <!----> 
        <!----> 
    </ul>
    <!----> 
</div>
```
I noticed that there is redundant &nbsp; after the 'Toggle View' button, but I don't know why, and after reading the source code, I cannot find anything too.
The other browsers include Microsoft Edge, Firefox does not reproduce.

**Comment by niemyjski** [comment]
I thought I fixed this in the latest nightly, can you please confirm?

**Comment by edwardmeng** [comment]
Yes, it has been fixed.
