### ISSUE TITLE
Don't reference stripe.com when the STRIPE_PUBLISHABLE_KEY has no value

### ISSUE THREAD

**Issue by edwardmeng** [exceptionless/Exceptionless.UI#150]
Yesterday we suffered an serious breakdown in our self-host exceptionless. After investigation, we found that the stripe.com cannot be accessed for several hours, but we did make use of it. So please consider that do not reference any script from stripe.com when the STRIPE_PUBLISHABLE_KEY has no value in the app.config.js.

**Comment by niemyjski** [comment]
The new version of angular-stripe is supposed to bring this in but I've been hesitant to update to it. This is something we should update.

**Comment by edwardmeng** [comment]
The 'https://js.stripe.com/v2/' was blocked again that we cannot open the exceptionless dashboard for hours.

**Comment by niemyjski** [comment]
doh, this should be fixed in the angular 6 branch. We need to finish this up and get it merged over.
