### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.UI#151]
The current dates in Exceptionless are always formatted according to US style. I do not live in the US, nor do I have anything set to US, and would like to read dates in my local date format.

**Comment by niemyjski** [comment]
We would be open to having a pr for storing an option in user settings to control how to display the date format or maybe even look at the browsers local. I'm closing this for now as this is not something we intend to do in the near future but would be willing to accept a pr for

**Comment by niemyjski** [comment]
If more users comment on this, we can revisit it sooner than later
