### ISSUE TITLE
Occurred on ...

### ISSUE THREAD

**Issue by Phyxion** [exceptionless/Exceptionless.UI#152]
At 'Extended Data', there are no spaces between the (... ago), for example:
Aug 28, 2017 3:07:05 PM (20 hours ago)
vs (on all other tabs)
Aug 28, 2017 3:07:05 PM ( 20 hours ago )

**Comment by Phyxion** [comment]
I've already looked at the source and I think it's because some are on a new line and others are not, e.g. 
https://github.com/exceptionless/Exceptionless.UI/blob/7abdfab1beeb84cc7c364d7941a2e25db9385963/src/app/event/tabs/promoted.tpl.html
vs
https://github.com/exceptionless/Exceptionless.UI/blob/7abdfab1beeb84cc7c364d7941a2e25db9385963/src/app/event/tabs/simple-error.tpl.html

What do you prefer? I'm not entirely sure where all the ..tpls stand for but both 'formatting' options are used several times so it might be easier for you to just make them all identical (+ I don't have npm installed at the moment).

**Comment by niemyjski** [comment]
Please feel free to put them on the same line, this should resolve the issue with line spacing. Also, nice catch :)

**Comment by Phyxion** [comment]
Yes, I noticed it during fast switching of the tabs (was checking for some additional data).

**Comment by niemyjski** [comment]
Thanks for the pr, it should be available shortly :)
