### ISSUE TITLE
Next/Back buttons on event is not aware of the current stack

### ISSUE THREAD

**Issue by tekmaven** [exceptionless/Exceptionless.UI#16]
In Exceptionless 1.0, when viewing an error from a stack, clicking the next/back buttons on the error would allow you to quickly move between the errors in the stack.  In Exceptionless 2, it seems that the next button just takes you to the next error, is not an error from the same stack in most cases (high volume of errors in our projects).

**Comment by niemyjski** [comment]
This will be fixed in one of the next pushes. This has to do with the previous and next event logic is very generic and will be used in the future for different views. We need to filter this to a specific stack when you navigated from a stack.

**Comment by niemyjski** [comment]
Since the event page doesn't have the current stack id when the view is loaded I need to do a small server side change, which I'm currently blocked on. I'll try and get this out as soon as I can.

**Comment by niemyjski** [comment]
I've fixed this issue and will deploy the fix over the weekend.

**Comment by niemyjski** [comment]
This fix has been deployed!
