### ISSUE TITLE
Please Add API Key Can Edited

### ISSUE THREAD

**Issue by Varorbc** [exceptionless/Exceptionless.UI#166]
![image](https://user-images.githubusercontent.com/5714438/39983875-cf0a9a14-578b-11e8-8bbd-bb963fab7558.png)

**Comment by niemyjski** [comment]
Hey, thanks for your feedback. We don’t have any plans currently  to add this functionality as it would be a security issue. Also, we have to ensure we generate unique keys in a multi tenant system. Having two people create the same key, exposes the other persons key. I’m guessing your use case is you deleted it and want to add it back?
