### ISSUE TITLE
TV friendly exception dashboard

### ISSUE THREAD

**Issue by erichexter** [exceptionless/Exceptionless.UI#17]
I would like to have a TV friendly view of the Exception Dashboard. Our dev ops team monitors our application with a series of dashboards, we currently project the Exceptionless Exception Dashboard but the Most Frequent and Most Recent sections get lost on a big screen, It would be great to just have the top cards and a large view of the history graph, that way as someone comes in , they can correlate a change in the exception pattern to a time in the day easily.

![image](https://cloud.githubusercontent.com/assets/114692/6847082/bf156304-d391-11e4-8b5b-35835a8f21f2.png)

**Comment by niemyjski** [comment]
:+1:

**Comment by niemyjski** [comment]
I did some quick looking and I think we should use [screenfull.js](https://github.com/sindresorhus/screenfull.js) for this and write a directive that triggers this.

**Comment by erichexter** [comment]
Actually, the screenfull would work if you have a machine hooked directly to a large monitor, but for a chrome cast it is not necessary. It only projects the inside of the browser not the entire window.

**Comment by niemyjski** [comment]
I thought the chrome cast had the feature to show your whole screen (maximised). But what happens if the browser content goes full screen? Can you try the screenfull demo on the chrome cast and let me know?

**Comment by erichexter** [comment]
it does help if you go fullscreen, but the down side is you cannot keep
using the machine once you force it to fullscreen. In stead, I actually run
multiple browsers minimized but cast the tabs to TVs in the room. That way
there is still a usable machine that also casts the dashboards.

Eric Hexter

blog | http://Hex.LosTechies.com
info | http://www.linkedin.com/in/erichexter

**Comment by niemyjski** [comment]
What if you just zoomed in on the tab content and set the tabbed window size to cover just the dashboard? I'm not sure what the correct fix for this would be if you can't go full screen (maybe zoom)?

**Comment by niemyjski** [comment]
@erichexter did you find a solution for this? I'm going to close this issue as you can currently go into full screen mode. We also are talking about the the ability to build your own custom dashboards https://github.com/exceptionless/Exceptionless/issues/141
