### ISSUE TITLE
Data too large error

### ISSUE THREAD

**Issue by capqueen** [exceptionless/Exceptionless.UI#173]
There are some errors in my log,how to slove this error?
`2018-06-15 12:51:57.2023   60 ERROR Exceptionless.Core.Utility.EventStats Retrieving term stats failed: Failed to execute phase [query], all shards failed; shardFailures {[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201804][0]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201805][0]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201806][0]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201804][1]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201805][1]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201806][1]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201804][2]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201805][2]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201806][2]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201804][3]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201805][3]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201806][3]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201804][4]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201805][4]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]}{[3b2M5ENuTHG5PHiEU6ZlgQ][events-v1-201806][4]: CircuitBreakingException[[REQUEST] Data too large, data for [<reused_arrays>] would be larger than limit of [415550668/396.2mb]]} `

**Comment by niemyjski** [comment]
I've never seen this error before. My guess is elastic needs some extra memory (ram) or configuration required as suggested here: https://stackoverflow.com/questions/30811046/fielddata-data-is-too-large

**Comment by niemyjski** [comment]
Were you able to resolve this? In the mean time I'm going to close this as I don't think this is a ui issue.
