### ISSUE TITLE
An error occurred while logging in. Please contact support for more information.

### ISSUE THREAD

**Issue by simsq** [exceptionless/Exceptionless.UI#174]

**Comment by simsq** [comment]
![image](https://user-images.githubusercontent.com/22512558/41894614-0b37a59e-7952-11e8-99a4-cc709ece6a19.png)

**Comment by niemyjski** [comment]
Hello,

Can you please open your network tab in your browser and see what error you are getting. Also is this a self hosted environment?

**Comment by simsq** [comment]
![image](https://user-images.githubusercontent.com/22512558/41948539-d7944a64-79ef-11e8-8ae4-a06d15185a83.png)

**Comment by simsq** [comment]
![image](https://user-images.githubusercontent.com/22512558/41948565-eea68b0e-79ef-11e8-9ef3-29217b7589f3.png)

**Comment by niemyjski** [comment]
Can you please show the response for the 401. It could just be you need to register an account or you locked yourself out (you'd need to look in the logs to see if you locked yourself out). Also, I'd try the troubleshooting guide: https://github.com/exceptionless/Exceptionless/wiki/Self-Hosting#troubleshooting
