### ISSUE TITLE
All Projects restricted to 100 items

### ISSUE THREAD

**Issue by jdtaylor91** [exceptionless/Exceptionless.UI#176]
Is it possible to increase the limit of how many projects are returned in the 'All Projects' menu? Currently the XHR request is specifying a limit of 100, it would be great if there was a setting somewhere where we could increase that.

Alternatively if this is limiting to 100 by design could the Admin > Projects listing be improved so that it is ordered alphabetically by project name? Currently there is no ordering or search capability so it is hard for us to navigate to our projects.

**Comment by niemyjski** [comment]
I agree that this needs to happen. We are currently rewriting the ui and will make some of these changes. In the mean time would you mind submitting a pr for increasing the page size or sort order?

**Comment by vytas-dauksa** [comment]
Where can we track progress? Also are there any more technical details available in case someone is able to help out? I see backend fix was rejected couple years ago - https://github.com/exceptionless/Exceptionless/pull/318 and pagination was suggested instead

**Comment by ejsmith** [comment]
@jdtaylor91 yeah, I think more than 100 in that list is going to be a pretty bad UX. I'd rather see us limit it to something even smaller than 100 and if it's more than that it would have a search box on the dropdown where you could search for projects. I would love to see that Admin Projects page improved. Are these things that you would want to take a stab at?

**Comment by jdtaylor91** [comment]
@ejsmith I agree - a search box within the projects selector would be great. Unfortunately, i don't have the time to progress any of this at the moment.

**Comment by niemyjski** [comment]
I increased the max page size on projects for now, this may change at a future date until we get the new ui out and we get smarter project updates via state management, paging as well. I'll get the server deployed and then I'm probably going to implement this as well as #143

**Comment by niemyjski** [comment]
@jdtaylor91 this should be going out to prod soon and will be available via the docker ci images. Can you please log a new issue for adding filtering to the project and organization lists.

**Comment by jdtaylor91** [comment]
Perfect! Thank you for your help on this.

**Comment by niemyjski** [comment]
Search on project list page will also be going out shortly.
