### ISSUE TITLE
When typing version for "Mark Fixed", it auto-inserts revision number after typing first digit of minor version

### ISSUE THREAD

**Issue by boydpatterson** [exceptionless/Exceptionless.UI#178]
Impossible to type a version like "2.15" because it will auto change to "2.1.0" as soon as you type the "1".  Equally troubling if you try to type "1.2.3" because typing the "2" changes it to "1.2.0" and you have to backspace over the "0" to type the proper revision number.

**Comment by niemyjski** [comment]
Sorry for the late response we will get this fixed.
