### ISSUE TITLE
Sessions: "View Active" inverted

### ISSUE THREAD

**Issue by jespersh** [exceptionless/Exceptionless.UI#179]
When visiting the Sessions Dashboard, then the "View Active" is off and all sessions are displayed. flipping it to on, then nothing changes on this first flip. Flipping it back to off however clears the board and flipping it to on shows all events again. I _think_ this is inverted of what is intended.

![udklip-active-off](https://user-images.githubusercontent.com/1004198/48341452-5e235e00-e66d-11e8-916e-f4986db55b70.PNG)

![udklip-active-on](https://user-images.githubusercontent.com/1004198/48341466-64b1d580-e66d-11e8-84ba-3772ccd96a3d.PNG)

**Comment by niemyjski** [comment]
When it's off it should show everything. Are there any errors in the console?

**Comment by jespersh** [comment]
No errors are showing up. It works the same in Chrome and Firefox (video below)

![sessions](https://user-images.githubusercontent.com/1004198/48410927-597baa00-e740-11e8-83eb-0ccb4989a007.gif)

**Comment by niemyjski** [comment]
What is the project id that you are seeing this behavior on?

**Comment by jespersh** [comment]
> What is the project id that you are seeing this behavior on?

All of them individually and in "All Projects" and setting time to "All time" or "Last 24 hours" has no difference.

**Comment by niemyjski** [comment]
Is this still an issue? If so can you give me the project id from the url so I can take a closer look.  In the mean time I'm going to close this until I have more information.

**Comment by jespersh** [comment]
The only project we have that uses sessions: 5a7805ada3fbe53c08f78888
What I noticed was this in addition to what I already described:
1. Visit sessions dashboard for project in "Last Hour".
2. Set "View Active" to checked.
3. Observe nothing happens, both active and inactive sessions are shown.
4. Change time range to "Last 24 Hours".
5. Only Active sessions are shown now.
6. Uncheck "View Active".
7. Still only active sessions are shown.
8. Change time to "Last Hour".
9. Viewport updates to show both active and inactive sessions again.

**Comment by niemyjski** [comment]
Thanks for the follow up, we'll take a look

**Comment by niemyjski** [comment]
My apologies for not updating this issue or getting this deployed sooner. This was fixed in December: https://github.com/exceptionless/Exceptionless.UI/commit/7c8731153f35f8097acedb9a76a3c00b100e85db we'll get a push out ASAP.
