### ISSUE TITLE
OpenId Connect (OIDC) feature request

### ISSUE THREAD

**Issue by yang-xiaodong** [exceptionless/Exceptionless.UI#182]
Hello,

Is there a plan to support custom OpenId Connect for UI? 

Thanks

**Comment by niemyjski** [comment]
Hello,

Not at this time. But if someone wants to start a discussion about how to support it, as well as a pr for it it's something we will definitely consider!

**Comment by niemyjski** [comment]
I'm going to close this, but if more people comment on this or someone wants to submit a pr we'll accept it.
