### ISSUE TITLE
As user I want to see ability to set custom date with range until now

### ISSUE THREAD

**Issue by Naggorny** [exceptionless/Exceptionless.UI#19]
To do:
- provide user ability to set custom date like: from 03.31.2015 10:00 until now

**Comment by niemyjski** [comment]
@Naggorny would you mind submitting a pull request for this?

**Comment by niemyjski** [comment]
You could currently do this by doing the all time filter and then do date:03.32.2015-now

**Comment by niemyjski** [comment]
I'm going to merge this into https://github.com/exceptionless/Exceptionless.UI/issues/11 as we plan to make improvements to filtering and date selection in the near future.
