### ISSUE TITLE
How to use Git code to build Exceptionless.UI for IIS site files

### ISSUE THREAD

**Issue by Cloud33** [exceptionless/Exceptionless.UI#190]
How to use Git code to build Exceptionless.UI for IIS site files

**Comment by niemyjski** [comment]
We don't support hosting in IIS, only via docker containers. If you wish to try and get it running on iis, you could manually build the website and use this old web.config but we will not longer be supporting iis (https://github.com/exceptionless/Exceptionless.UI/blob/v2.7.1/src/web.config). If you need any direction on using docker please let us know.

**Comment by Cloud33** [comment]
ok
