### ISSUE TITLE
How to configure OAuth2?

### ISSUE THREAD

**Issue by stulzq** [exceptionless/Exceptionless.UI#194]
I didn't find information on the exceptionless wiki.

Thanks.

**Comment by niemyjski** [comment]
Hello,

You need to Add an OAuth connection string with the settings (https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Core/Configuration/AuthOptions.cs) You can do this via docker compose or passing an environment variable to docker https://github.com/exceptionless/Exceptionless/blob/master/src/Exceptionless.Web/appsettings.Production.yml#L11

**Comment by niemyjski** [comment]
Please let us know if you have any questions.
