### ISSUE TITLE
Log Messages with more than two lines are visibly concatenated

### ISSUE THREAD

**Issue by ocbaker** [exceptionless/Exceptionless.UI#2]
Some (very silly) logger in a library we use reports exception in plain text. We then report those the exceptionless via the log section.

One problem is that when the log message come in it often holds a full stack trace and I want to be able to get at  that to see what is going on. However even in the event view of a single item the only way the view the whole message field to to hover over the text and see a tooltip with the full message.

Preferably being able to expand and collapse the message field would be better since it would also work on mobile devices too. You can't hover on a mobile device.

**Comment by niemyjski** [comment]
I'm kind of split on this, if your event type is a log message then I could see wanting not to trim it but in the case that it's any other event type two lines is a lot of content. I agree that we could make this better on mobile to show all the text. It would be nice to have a touch gesture. What are your thoughts about only trimming non log messages?

Do you know when the library you use is reporting an exception?

**Comment by ocbaker** [comment]
We kind of know but only by parsing the log. I think perhaps if you could at least have a raw data page like the extended data perhaps that might solve the issue. But I don't think trimming data is helpful as a developer.

As a developer if for some reason there is some pertinent information being withheld from me because my message was too long then it might not have been worth reporting that at all. Perhaps a long message field or something along that line is an option too?

I think at least if messages are going to be concatenated in the UI then you should consider putting a restriction on field size for the messages in API and make that a standard for the API. Since if you can put 2,000 characters into a field but if you want to access more than 200 then you need to directly query the API yourself then I don't think that makes much sense.

**Comment by niemyjski** [comment]
Yeah, I agree with you on the restriction. I'll talk with the team and see about extending this message field size in the ui.

**Comment by niemyjski** [comment]
I increased the default line limit to 4 for now. I'd like to have it so you can click to to view the raw message.

**Comment by ocbaker** [comment]
I quite like that idea. I'm fine with having a shortened message in the current view, but I still need an ability to access the full message. I think the solution you've suggested is very appropriate.

**Comment by niemyjski** [comment]
Merging into https://github.com/exceptionless/Exceptionless.UI/issues/56
