### ISSUE TITLE
status:open OR status:regressed 

### ISSUE THREAD

**Issue by mbpframework** [exceptionless/Exceptionless.UI#204]
status:open OR status:regressed ,can not find any conten,but the elasticsearch has content

**Comment by niemyjski** [comment]
Thanks for reaching out to us, what is the status of the stacks in elastic? They could be marked as fixed, ignored or discarded and then they won't show up in the ui unless you view a status report or put `*` into the search box.

**Comment by mbpframework** [comment]
thanks,
