### ISSUE TITLE
Copy text is appending \r\n

### ISSUE THREAD

**Issue by PhyxionNL** [exceptionless/Exceptionless.UI#206]
A long outstanding bug which I thought I had reported already, but it seems not.
The copy button of stack traces (and possibly other text, but I haven't tested that) simply appends "\r\n" after each line to the clipboard, rather than being an actual break.
So you'll see this added to clipboard:
```text
HelloWorld.Exception\r\nSomeThingHere.Something\r\nAnotherThing
```

What is should add:
```text
HelloWorld.Exception
SomeThingHere.Something
AnotherThing
```

Copying text manually works but I assume this should be fixed 🙂

**Comment by ejsmith** [comment]
Yeah, that sucks. Any chance you can take a look at fixing that issue?

**Comment by niemyjski** [comment]
I haven't been able to reproduce this. I'm using Edge Latest. Are you still seeing this and if so, can you let me know what browser and also paste the event json here so I can attempt to reproduce.

**Comment by PhyxionNL** [comment]
> 
> 
> I haven't been able to reproduce this. I'm using Edge Latest. Are you still seeing this and if so, can you let me know what browser and also paste the event json here so I can attempt to reproduce.

Seems to work now in latest Firefox as well.
