### ISSUE TITLE
Show information for inner exceptions not just outer exceptions

### ISSUE THREAD

**Issue by wingers999** [exceptionless/Exceptionless.UI#209]
As already discussed with Blake and Eric

When an exception contains inner exceptions it would be very useful if the additional data / information from these could also be shown.

We know the data is uploaded as it is in the JSON so it just needs to be shown in the UI.

Sometimes as per example below the outer exception doesn't contain anything useful to allow you to diagnose / fix the problem.

![image](https://user-images.githubusercontent.com/10872799/115014218-eeeb6d00-9ea9-11eb-92e1-76b7acec0a57.png)

Whereas the inner exception (in this case the System.Net.WebException) contained exactly what I needed to know to be able to fix the issue.

![image](https://user-images.githubusercontent.com/10872799/115014294-0d516880-9eaa-11eb-8bf2-56d124e2ce03.png)

Below is a mockup of how I think it should look

![image](https://user-images.githubusercontent.com/10872799/115014535-5f928980-9eaa-11eb-95b2-843df5ce1258.png)

As a minimum for now it would be good to have a tab showing the raw JSON data rather than having to click button to copy it to clipboard and then paste it somewhere else to view it

![image](https://user-images.githubusercontent.com/10872799/115014555-68835b00-9eaa-11eb-8c56-2754b5ada310.png)

But long term the UI really needs to show information from all exceptions whether outer or inner as it is a pain having to go through the JSON each time to find causes of errors, and in my mind defeats the whole point of using a tool like this

**Comment by ejsmith** [comment]
Yeah, @niemyjski I'd love for us to add an option to easily see the full event JSON as an easy win. But I think the root issue with this is that we need to do a better job of bubbling the right info to the top. Ideally, we don't want people to have to dig into inner exceptions to see the issue.

**Comment by niemyjski** [comment]
This will go out when I tag the next release. I want to get the dialog for showing / copying json (working on that now) in there before pushing
