### ISSUE TITLE
Allow access easly to billing

### ISSUE THREAD

**Issue by matteomigliore** [exceptionless/Exceptionless.UI#21]
A link to the billing in "organization/list", in a ad-hoc column, should be useful for administration people to download the billing.

**Comment by niemyjski** [comment]
At the very least I think we should add an actions button to view the billing as well as change the plan.

**Comment by matteomigliore** [comment]
The problem is make the billing, visible, I think that an action into the dropdown does not solve it.

**Comment by niemyjski** [comment]
The issue (I have personally) with adding a new column is that it doesn't work on mobile / really makes everything much smaller. If the action drop down doesn't work then to me it kind of sounds like a usability bug. We need it really discoverable... I'll play around with adding a column.

**Comment by niemyjski** [comment]
I'm closing this as it's easy to get to the organization list and organization billing tab. We also send out emails with the invoice. If there is anything more that we can do please let us know.
