### ISSUE TITLE
On "Fixed" stack page show all data as if you used "*" filter.

### ISSUE THREAD

**Issue by mpawelski** [exceptionless/Exceptionless.UI#212]
Hi,
thank you for such a great product! I've recently started using Exceptionless and notices one behaviour that I thought is strange/intuitive/buggy.

When you mark you stack as "fixed" and then go to this stack then all top counters and data about this stack are shown as if there were zero exceptions. I figured out that it's because by default fixed and hidden exceptions are not shown and you need to put `*` as filter query. But I'm explicitly on stack page which status is "Fixed". I think for such pages empty filter query should behave as if we used `*`.

![exceptionless_fixed_stack_counter](https://user-images.githubusercontent.com/2056282/123489631-b0450200-d612-11eb-9b55-db9900f93004.gif)

**Comment by niemyjski** [comment]
Hello,

Thanks for reporting this issue, it definitely does seem like a bug and we'll take a look

**Comment by niemyjski** [comment]
This will be fixed in the next release.
