### ISSUE TITLE
There are some websockets issueses.....

### ISSUE THREAD

**Issue by CoderRiker** [exceptionless/Exceptionless.UI#213]
![image](https://user-images.githubusercontent.com/88869889/129862565-e5428168-612b-4e6c-98db-19257a1e2076.png)

**Comment by niemyjski** [comment]
We'll need some additional information like:

-  what version are you running?
- how are you hosting?
- What is the error response?
- Have you verified the api endpoint is valid? <http://host:5601/healthy>

**Comment by CoderRiker** [comment]
UIVersion:3.1.1

**Comment by CoderRiker** [comment]
UIVersion:3.1.1
APIVersion:7.0.9
Hosting:IIS
The previous problem does not affect the use, but the following problem has occurred
![image](https://user-images.githubusercontent.com/88869889/129995273-35f728e0-9dd0-469d-b07c-f56206be63fc.png)

**Comment by CoderRiker** [comment]
Due to this problem, I cannot receive the submitted log

**Comment by niemyjski** [comment]
This sounds related to https://github.com/exceptionless/Exceptionless/issues/955 as websockets are failing because they can't resolve the auth token. Also please note that you have to have web socket support something our docker container supports out of the box.
