### ISSUE TITLE
Session Time is the opposite

### ISSUE THREAD

**Issue by PhyxionNL** [exceptionless/Exceptionless.UI#214]
![image](https://user-images.githubusercontent.com/7643972/107057746-10f2b000-67d4-11eb-834c-10e84bf743b9.png)

==> "After a few seconds" should be "after 11 minutes" (and vice versa). The events start at the bottom, i.e. the "after 11 minutes" is on 8:47 PM and "after a few seconds" is 8:58 PM.

So basically the events should be ordered as-is, but all descriptions should be reversed.

**Comment by niemyjski** [comment]
This has been fixed in 3.1.2

**Comment by PhyxionNL** [comment]
Can confirm it's now fixed 🎉
