### ISSUE TITLE
Ability to control the front-end language via local settings

### ISSUE THREAD

**Issue by lnstock** [exceptionless/Exceptionless.UI#217]
刷新页面后，左侧导航重新变为英文。但是强制刷新（Ctrl+F5）则没有问题。
--------------------------------------------------
After refreshing the page, the left navigation changes to English again. But force refresh (Ctrl+F5) is not a problem.

**Comment by niemyjski** [comment]
Are there any network errors shown in your Browers network tab loading the translation json  files when you refresh (f5)?

**Comment by lnstock** [comment]
No errors.

**Comment by niemyjski** [comment]
Can you try tracking this down by debugging this app. I'd probably set a breakpoint or logging here: https://github.com/exceptionless/Exceptionless.UI/blob/master/src/app.js#L71 and see what's happening when you refresh.

**Comment by lnstock** [comment]
![ui](https://user-images.githubusercontent.com/36703881/148176405-1af61bcc-fc47-49ea-9ac8-a0c97c074532.gif)

看GIF，刷新后变回英文的情况不是每次都会出现，我调试了UI源代码，出现英文的时候，lang = zh-cn。
--------------------------------------------------------------
Look at the GIF, the refresh back to English is not always the case, I debugged the UI source code, when the English appears, lang = zh-cn.

**Comment by niemyjski** [comment]
I'm kind of clueless on why half would be in English and the other half not. Are there any errors in the console? Could you see if this is an issue in a browser that has no extensions. It would also help if there was an exact steps that reproduce it every single time, is it just refreshing the login page (can you reproduce in a different browser).

**Comment by LEIRONGHUA** [comment]
I also encountered the same problem.

**Comment by lnstock** [comment]
I was using Edge browser before, then I purposely downloaded Firefox without any extensions and had the same problem, and no error occurred in the console.

**Comment by niemyjski** [comment]
If one of you could debug this and figure out the root cause that would be amazing. I'm trying to remember how I changed my browsers local or if I just hard coded it.

**Comment by 107295472** [comment]
It is better to add a Chinese and English switch to the page

**Comment by niemyjski** [comment]
It may be nice if we stored this setting in local storage and checked it on startup with a fallback if the key is not in local storage or error accessing local storage. Any chance you'd be willing to submit a pr for this?

**Comment by 107295472** [comment]
angular doesn't

**Comment by niemyjski** [comment]
I'm not sure what you mean by angular doesn't?

**Comment by 107295472** [comment]
angular  不会，提不了pr

**Comment by niemyjski** [comment]
Can you please post your replies in english.

**Comment by 107295472** [comment]
can not speak English

**Comment by niemyjski** [comment]
Hello,

We do not speak Chinese, if you could use https://translate.google.com/ we will do our best to communicate and understand the request.

**Comment by 107295472** [comment]
How to turn off 404 records

**Comment by niemyjski** [comment]
> How to turn off 404 records

Please create a new issue for any new question. You can turn off 404 collection through project configuration: https://exceptionless.com/docs/project-settings/#example

To discard all 404s in general you would use a wildcard *:

KEY: @@404:*
VALUE: false

**Comment by 107295472** [comment]
thanks.    request to remove cnd

**Comment by niemyjski** [comment]
We'd be willing to accept a pr for a language selector.
