### ISSUE TITLE
Getting Started Issues

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.UI#23]
List out the requirements for doing local dev:

* Install Node JS

We should also run through the setup on a fresh vm and check for issues as [one user ran into the following issue](https://github.com/exceptionless/Exceptionless/issues/84): 
![image](https://cloud.githubusercontent.com/assets/1020579/7120905/4671b382-e1d6-11e4-8c9e-acd11fb08b39.png). We may want to specify that if you are on windows, than you should be putting it at the root of the drive because of the file path limitation.

**Comment by KasperLK** [comment]
I'm not sure if it's problem in Windows. But when I tried using "Node.js Tools for Visual Studio" I got a warning about the 260 character path from Visual Studio.
 I tried moving the Exceptionless.UI to the root, and I even tried renaming Exceptionless.UI to E, but Visual Studio still complained.

**Comment by niemyjski** [comment]
Hmm, I wonder if it's just a generic warning that the addin gives you.

**Comment by KasperLK** [comment]
I think it was from the Node.js Tool. It presented me with some option to try to shorten the path (I can't remember what it was called), but that also failed. Visual Studio could not run the project.

**Comment by KasperLK** [comment]
I got a bit further, but I will try from clean if it works.

Install Bower should be added to requirements, and also Git as Bower requires Git.

**Comment by KasperLK** [comment]
"grunt server" command gives me this error.
![grunt](https://cloud.githubusercontent.com/assets/11861088/7122533/6056659a-e21c-11e4-8bea-99ac02036592.png)

**Comment by niemyjski** [comment]
There is no grunt task for server. It's grunt serve

**Comment by niemyjski** [comment]
Were you able to get it working?

**Comment by KasperLK** [comment]
I'm trying to delete the Exceptionless.UI to do a clean install, but the path length is a problem.

**Comment by niemyjski** [comment]
Yeah, that is a known issue with node and windows :(.

**Comment by niemyjski** [comment]
I'd recommend doing an npm install over the current path.

**Comment by KasperLK** [comment]
Moving Exceptionless.UI to the root still gives me a path that is to long. Renaming the folder to E solved the problem.

**Comment by niemyjski** [comment]
I've checked it out to C:\Code\Exceptionless.UI and have had no issues on Windows 8.1

**Comment by KasperLK** [comment]
I did a clean install with Exceptionless.UI located at C:\Code\Exceptionless.UI instead and it works.
I will try again in the original folder to see if it also works there.

Requirements seems to be:
- Node.js
- Bower
- Git

**Comment by niemyjski** [comment]
Thanks for the heads up.

**Comment by KasperLK** [comment]
I got it all up and running now, but there seems to be some problems with Organizations and Projects.
I can see them both under Admin, but not in the projects dropdown, and I also see the help message that tells me to create a new project.
I also can't log exceptions to it. The log files gets passed from the storage folder.

**Comment by niemyjski** [comment]
We've updated the install docs and requirements.
