### ISSUE TITLE
Difficult to tell when results are filtered

### ISSUE THREAD

**Issue by edgarecayce** [exceptionless/Exceptionless.UI#25]
If you don;t know that the calendar/filter icons light up green when there is a filter applied, it can be confusing when you see no exceptions (or fewer than you expect).  maybe a notification can pop up or something indicating why you see no results?

**Comment by niemyjski** [comment]
What do you think of:
* having a notifications box at the top when the search results are empty.
* having the list also mention checking your filters.
* having the green filter icons use animations that differ in intensity?

**Comment by edgarecayce** [comment]
I think the first two are great ideas - third one might be too much.

**Comment by niemyjski** [comment]
Thanks for your feedback.

**Comment by niemyjski** [comment]
I'm merging this in as a duplicate to this issue: https://github.com/exceptionless/Exceptionless.UI/issues/33 This is something we will get taken care very soon! Thanks for your feedback!
