### ISSUE TITLE
Lists don't always clear after bulk mark-as-fixed

### ISSUE THREAD

**Issue by BillHenning** [exceptionless/Exceptionless.UI#27]
I notice that when using Exceptionless in IE and have a couple pages of exceptions in stacks that are fairly small, I do the checkbox to select all in Most Frequent, and Bulk Action / Mark as Fixed. Then the final set of exceptions comes up and I repeat. The toast says It cleared them but they still appear in the list.  If I F5 refresh the page, they are gone, so the UI just didn't update.

**Comment by niemyjski** [comment]
Does this happen when you are paged or always on the first page. About how many exceptions are in each stack (e.g., <100)?

**Comment by BillHenning** [comment]
I’ve only noticed it when having multiple pages but might happen more too.  I’ll pay more attention next time.  There aren’t many exceptions in the stacks (definitely much < 100).

**Comment by niemyjski** [comment]
This has been fixed in the latest builds.
