### ISSUE TITLE
Events are sent to integration across projects

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless.UI#28]
I have setup five projects, and configured a web hook integration on one of them.
Events from the other four projects are all sent to that web hook. I have no integration setup on the other four projects.

I think it's a bug, but it's also a nice "feature". If you fix this bug, could you please implement an option to configure an integration to work across all projects that don't have their own integration setup.

**Comment by niemyjski** [comment]
When you specified your webhook, how did you create it? If you created it via the api did you specify it with an organization id and project id or just organization id?

**Comment by KasperLK** [comment]
I createded it from the UI.

**Comment by niemyjski** [comment]
Thanks, I'll take a look into this and get it fixed. Our webhooks can be run via project or organization level. It sounds like it was created with both and it's running on both or that there is a bug where it's picking it up when it shouldn't.

**Comment by KasperLK** [comment]
And it can only be setup on organization level via the api?

**Comment by niemyjski** [comment]
Yes, but to be honest this needs more testing as we've only tested it via project level but we designed it to do both. If you could just specify the organization id and let us know that would be great. But please keep in mind you might not be able to delete it or view it via the UI currently but could manage it via the api

**Comment by niemyjski** [comment]
@KasperLK Are you still running into this? I haven't ran into this behavior at all since you initially reported it.
