### ISSUE TITLE
Additional data of inner exception is not visible

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.UI#29]
Use case here is an `AggregateException` with one inner `DbEntityValidationException`. Normally the `DbEntityValidationException` would show the errors, but because in this case it is an inner exception it isn't shown. I was able to figure out what caused the exception by looking at the raw JSON data, so the data is there.

Also worth noting that there's another issue with AggregateException, depending on what issue gets fixed first can cause an relation, depending on the chosen strategy. See https://github.com/exceptionless/Exceptionless.Net/issues/15

**Comment by niemyjski** [comment]
Yes, I think we should show the inner extended data if it exists under an inner exception additional data..

I'm not sure what you do in this case tho:

Additional data
  -blah
  InnerException Additional Data (has none)
     InnerException Additional Data
     -blah

**Comment by niemyjski** [comment]
Merged into https://github.com/exceptionless/Exceptionless.UI/issues/44
