### ISSUE TITLE
filter requires a field specifier

### ISSUE THREAD

**Issue by ocbaker** [exceptionless/Exceptionless.UI#3]
If no filter type is specified in the search would it be possible to default to message?

**Comment by niemyjski** [comment]
Can you please expand on this. What do you mean by no filter type (The all view?)? What message would you like shown?

**Comment by ocbaker** [comment]
If I want to search for "npc error" in the message field I need to put:
```
message:npc error
```
Why not have the option to (if you want to search the message field, or just do a general query perhaps) be able to not put a specifier? So my filter would become:
```
npc error
```
Then that would default to searching the message field and perhaps in the future would even search all fields?

**Comment by niemyjski** [comment]
you need to put it in quotes as any space is considered a start of a new search term. In this case error would be searching all fields for the term error. You can search for both, you just need quotes.

      message:"npc error"

 example:

     message:"My error message" or "My error message"


Are you not seeing this behavior?

**Comment by niemyjski** [comment]
I'm closing this unless you are not seeing this behavior. Please let me know if the quotes resolves this issue for you.
