### ISSUE TITLE
Footer appears on top of Bulk actions menu

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.UI#30]
There appears to be a z-index problem with the footer and the bulk actions menu, see screenshot.

![screen shot 2015-04-26 at 21 37 54](https://cloud.githubusercontent.com/assets/1292085/7339159/b876b584-ec64-11e4-9582-d63497d801f5.png)

**Comment by niemyjski** [comment]
Thanks for reporting this. I'll make sure this gets fixed in the 2.1 release.

**Comment by niemyjski** [comment]
@srijken would you mind submitting a pull request for this.

**Comment by niemyjski** [comment]
Fixed by https://github.com/exceptionless/Exceptionless.UI/pull/57! Thanks!!
