### ISSUE TITLE
Notifications: Descriptions and explanations of what an event is, what an error is.

### ISSUE THREAD

**Issue by mcbrireland** [exceptionless/Exceptionless.UI#32]
What is the difference between an error and an event? What is the difference between an error and a critical error? What is the difference between an event and a critical event? Thanks!

**Comment by niemyjski** [comment]
I think we should do something like this: 
![image](https://cloud.githubusercontent.com/assets/1020579/7352214/ef265060-eccf-11e4-879d-0bc8bb9ec814.png) or do you think it should just be a hover tooltip on "new errors" etc..?

**Comment by mcbrireland** [comment]
I think the question mark would be perfect.

**Comment by niemyjski** [comment]
@mcbrireland would you mind submitting a pull request for this

**Comment by niemyjski** [comment]
After further thought I'm going to close this. Please feel free to submit a pull request for this if you wish, but I think most users would know what an error is (you signed up for an error reporting service) and the target audience is developers/project managers. Please let me know your thoughts
