### ISSUE TITLE
As a user, I should know "where" I am and what I'm seeing at all times based on dynamic filter indicators

### ISSUE THREAD

**Issue by jmoeltjen** [exceptionless/Exceptionless.UI#33]
When a user changes a filter, whether it be project, timeline, search, etc, there is no indicators that tell the user what data is now being shown to them. Some things, such as history graph data point split are dynamically changed based on timeframe, which also adds confusion.

I suggest adding simple "breadcrumb" style indicators that tell the user what event silo they are in, what project they are viewing, what timeframe, and any search parameters. Then, I suggest adding a timeframe and data point split indicator to the history graph.

In the future, I would also love to see the ability to control data point split manually via hour/day/week/month selectors.

See mockup, below.

![exceptionless-filter-indicators](https://cloud.githubusercontent.com/assets/6110870/7398982/2564ff24-ee78-11e4-9b3c-87a594ef4768.jpg)

**Comment by niemyjski** [comment]
I really like this suggestion, We had some previous feedback that we could do either of these first two items as well:

* having a notifications box at the top when the search results are empty.
* having the list also mention checking your filters.
* having the green filter icons use animations that differ in intensity when they are first applied?

However, I think you suggestion works the best.

**Comment by niemyjski** [comment]
Merge into https://github.com/exceptionless/Exceptionless.UI/issues/11
