### ISSUE TITLE
Configure datetime format 

### ISSUE THREAD

**Issue by StefanoPaparesta** [exceptionless/Exceptionless.UI#36]
I want to configure the datetime format in UI. (24 h)

**Comment by niemyjski** [comment]
Currently we are displaying it in your local time zone. Where do you see yourself configuring this in the UI? Any specific reasons for wanting the 24 hour format over the 12?

**Comment by StefanoPaparesta** [comment]
I see this configuration at "Organizations" level, the reasons is simple, i'm Italian and the 24 hour format is simple to read.

**Comment by niemyjski** [comment]
I'm going to close this as it would be nice to have this configurable but we don't yet have localization support. If you wanted to submit a pr for this. I'd be more than happy to accept this.
