### ISSUE TITLE
Multiple projects with the same name in different organizations

### ISSUE THREAD

**Issue by modesto** [exceptionless/Exceptionless.UI#38]
I've installed ExceptionLess and ExceptionLess.UI in a local environment. If I try to create a new project with the same name of an existing project in other organization, it gives me an error saying that there is another project with the same name.

As I've understand reading ProjectController.cs, there can be multiple projects with the same name, but the current API call (check-name) is ignoring organizationId sending a null param.

Is there any way to change this behaviour?

**Comment by niemyjski** [comment]
We should probably add a route overload to allow you to specify the organization id. Previously we never wanted a project name to have the same name within your organization. But you have multiple organizations.

Would you mind sending us a pull request for this? A temp work around would be to invite a user to one of the orgs and then rename the project with that user and then remove the user.

**Comment by niemyjski** [comment]
Code in question: https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Controllers/ProjectController.cs#L370

**Comment by modesto** [comment]
Ok, I'll give it a try and send you a pull request.

**Comment by niemyjski** [comment]
@modesto Any luck creating a pull request for this?

**Comment by modesto** [comment]
@niemyjski I've made a pull request rigth now. It's my first pull request, so I'm sure I've do something wrong. The problem is that I've no idea how to change de UI side :(

**Comment by niemyjski** [comment]
This should be a server side only change I think because we update the UI based on the server side response. Thanks for the pull request, I'll take a look.

**Comment by modesto** [comment]
But if the UI is not sending the organizationId, How cand the server side knows if the name is unique in the organization?

**Comment by niemyjski** [comment]
I was thinking about this some more. I think we may need to include multiple routes and have the organization id optional and fall back to all the organization ids the user is in.

**Comment by niemyjski** [comment]
We have optional routes defined in the EventController.PostAsync with a prefix organization/id/project/check-name maybe?

**Comment by modesto** [comment]
I'm not sure I understand. Do you mean something like this?

```
[Route("check-name/{name:minlength(1)}/{organizationId?}")]
public async Task<IHttpActionResult> IsNameAvailableAsync(string name, string organizationId = null) {
```

**Comment by niemyjski** [comment]
Sorry, I just saw this reply.. Yes you would have two routes
```csharp
[Route("check-name/{*name:minlength(1)}")]
[Route("~/" + API_PREFIX + "/organizations/{organization:objectid}/projects/check-name/{*name:minlength(1)}")]
```

**Comment by niemyjski** [comment]
Could you update your pull request with this and I'll accept it

**Comment by niemyjski** [comment]
Thanks for the server side pull request! I've merged it in and it will be deployed shortly! https://github.com/exceptionless/Exceptionless/pull/155

The next step would be to update https://github.com/exceptionless/Exceptionless.UI/blob/master/src/components/organization/organization-service.js#L63 to take an optional parameter for organizationId and if it's set, then use the new route. Then we'd just have to update the usages on the add project page and manage project page to use this.

**Comment by niemyjski** [comment]
@modesto did you have any luck digging into this?

**Comment by niemyjski** [comment]
This has been fixed!
