### ISSUE TITLE
Indicate which project an event belongs to

### ISSUE THREAD

**Issue by KasperLK** [exceptionless/Exceptionless.UI#41]
I would like to be able to see which project an event belongs to, in the different overviews, eg. Dashboard, Most Resent, Most Frequent.
Maby with a colored label or just a colored icon with a mouse over help text with the project name.
Or some other way to quickly see what exceptions are from the same project.

**Comment by niemyjski** [comment]
Duplicate of https://github.com/exceptionless/Exceptionless.UI/issues/10
