### ISSUE TITLE
Extended data is not shown

### ISSUE THREAD

**Issue by woehrl01** [exceptionless/Exceptionless.UI#44]
The extended data is not shown in the UI. 

At least for:
* Environment Info 
* Request Info 
* Inner errors

**Comment by niemyjski** [comment]
I'll make sure we get this updated in the near future

**Comment by niemyjski** [comment]
We need to update the ui to show this so we can properly render a users custom properties like this: https://github.com/exceptionless/Exceptionless/issues/43
