### ISSUE TITLE
Installation instruction

### ISSUE THREAD

**Issue by silentnull** [exceptionless/Exceptionless.UI#5]
Hi,

Could you written simple help how I can install Exceptionless,UI on my IIS server ? Maybe better is used Linux with nginx ?

Pawel

**Comment by niemyjski** [comment]
I'll write up some docs. In the mean time, you can download a prebuilt zip [here] (https://www.myget.org/feed/exceptionless/package/nuget/Exceptionless.UI/). It's just an angular app so you can host it anywhere. You just need to update the app.config.js file.

Please let us know if you have any questions.

**Comment by niemyjski** [comment]
I just added some docs to the readme for setup. Please let me know if you have any feedback on setup.

**Comment by silentnull** [comment]
Hi,
Thank you for help me. Now, I have another question. I checked that you are hosting Exceptionless.UI on IIS8. You use iisnode extension or only rewrite to node.js application installed as service ? Can you write me short information ?

Regards,

Pawel

**Comment by niemyjski** [comment]
No, we only use iis to host the app (as we are already are paying to host the api server on azure websites). You can use anything to host the ui project as it's just an angular app. However the server project runs on asp.net.

Does this help?

**Comment by silentnull** [comment]
HI,
I started login page, but I don't signup or run authentication. I think that I have problem with communication with Exceptioless server because I have error on it:  0x80070002 - MapRequestHandler.

**Comment by niemyjski** [comment]
Hello,

If you are running Windows, I'd recommend using iis as this is not a node.js application.  If you can join our [chat room](https://gitter.im/exceptionless/Discuss), I can help walk you through this.
