### ISSUE TITLE
Add ability to copy / expand long messages for fields that overflow text

### ISSUE THREAD

**Issue by wshaddix** [exceptionless/Exceptionless.UI#56]
When viewing logged messages, if the message text is too long it cuts off and is not able to be viewed in its entirety. It is also not able to be selected/copied. 

Suggestion is to add a "Copy to Clipboard" button as well as a way to expand the text so that it is shown fully.

**Comment by niemyjski** [comment]
I've been thinking about this more. I think we need to do a double click action that expands it as well as selects all the text. What do you think? Would you be willing to take a look into this?

**Comment by niemyjski** [comment]
> I cannot see that issue 56 addresses my problem. What you have is a button to toggle the view in two modes: 1: one long line of text that wraps, 2: one long line of text that doesn’t wrap. 
None of the two modes displays the text as it is. It would be nice to be able to see the text in the same manner as in the “Stack Trace” box of the “Exception” tab.

**Comment by niemyjski** [comment]
I believe we have addressed this.
