### ISSUE TITLE
Bulk action selection is lost when data is refreshed in the background

### ISSUE THREAD

**Issue by srijken** [exceptionless/Exceptionless.UI#66]
Making batch changes against stacks by checking them is quite frustrating when queued operations are running in the background, because they keep getting unchecked when the grid is reloaded.

Try to make sure the checkmarks survive the data reload (ofcourse when the stack is gone from the view, it should no longer be checked)

**Comment by niemyjski** [comment]
+1

**Comment by niemyjski** [comment]
Yes, we need to do something for this as it can be very annoying. I was thinking if there was any selection then don't refresh. But what do we do when the selection is cleared (check for a flag and force update?)

**Comment by niemyjski** [comment]
Fixed in the fixed-in-version branch.
