### ISSUE TITLE
Add x-axis ticks and labels to charts

### ISSUE THREAD

**Issue by BillHenning** [exceptionless/Exceptionless.UI#69]
Right now it's difficult to ascertain the timeframe of charts without mousing all over them.  It would be much more user friendly to have appropriate x-axis ticks and labels that give a sense of the timeframe covered.

**Comment by niemyjski** [comment]
If we ever want to do multiline labels well have to get rid of the css hack (https://github.com/shutterstock/rickshaw/issues/158) and figure out a way to do a dynamic element.
