### ISSUE TITLE
Sort the project drop down list by most active

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.UI#7]
It would be nice to sort the project drop down list by most active to least active.

**Comment by Naggorny** [comment]
Hi niemyjski,
Actually, it would be nice to sort all projects as in OLD version, it is more useful then "by most active".

**Comment by niemyjski** [comment]
What do you mean by old version? By created date?

**Comment by Naggorny** [comment]
No, in OLD version in expanded project dropdown we saw sorting by projects from A to Z, for example ( http://screencast.com/t/hTqVHmshB ):
from the top of the list: 
[Dev]Backend
[Dev]EAPI
[Dev]UserReport
[Dev]...
[Prod]...
...
Do you have previous  version?

**Comment by niemyjski** [comment]
ahh, so you want them sorted alphabetically as we may have done in 1.x. Is that correct?

**Comment by Naggorny** [comment]
Yeaaa, just the same behavior

**Comment by niemyjski** [comment]
I'll make this happen :+1:

**Comment by Naggorny** [comment]
I look forward to implrmrntation

**Comment by niemyjski** [comment]
This will be fixed when we deploy the next client release (soon).

**Comment by Naggorny** [comment]
Thank you, implementation is good!

**Comment by niemyjski** [comment]
:+1:
