### ISSUE TITLE
On Sessions page chart, show users as a second series

### ISSUE THREAD

**Issue by BillHenning** [exceptionless/Exceptionless.UI#70]
It's useful to track your user counts alongside the sessions so you know if a small group of users are triggering most of the sessions or there are a lot of users only running the app once or twice.  Please add a second Users series to the chart that overlays the current Sessions series, since user count will always be <= session count.  You should already have the data to add this series without too much trouble.

**Comment by BillHenning** [comment]
This looks great but right now the sessions series is stacking on top of the users series.  They should not be stacking but should be two distinct series showing absolute values on the same y-axis.  Otherwise it's misleading me thinking my session count at any point in time is larger than what it really is (and what the tooltip shows).

**Comment by niemyjski** [comment]
Can you create a new issue for this as it affects all charts and not just this one.
