### ISSUE TITLE
Show usage on organization billing page with plan stats

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.UI#73]

**Comment by BillHenning** [comment]
Yes, please list out our usage as well as maximums per the current plan so we can see all that info together.

**Comment by BillHenning** [comment]
Please also show the period reset date and how many days left until that reset date.  That way we know if we need to throttle reporting or not when we are getting close to limits.

**Comment by niemyjski** [comment]
Fixed via https://github.com/exceptionless/Exceptionless.UI/commit/3227e72f44aaa91d2fda8e6c031daf0e582f6840
