### ISSUE TITLE
Show a toast notification when you've been added to an organization

### ISSUE THREAD

**Issue by niemyjski** [exceptionless/Exceptionless.UI#76]

**Comment by caesay** [comment]
When you get added to an organization there's a good change you're not looking at exceptionless at exactly that second, so it would need to be shown the next time you login or re-focus the tab in that case, right?

Maybe just better to send an email (do you already do that?)

**Comment by niemyjski** [comment]
We send an email already, but we also push a notification down to the client via signalr so we'd just need to show a toast using the notification service when we get that message :)
