### ISSUE TITLE
Organization list page should clarify what stacks/events numbers are

### ISSUE THREAD

**Issue by BillHenning** [exceptionless/Exceptionless.UI#77]
Thanks for all the organization detail page updates to show event consumption.  That's good stuff.  I was confused this morning though looking at the organization list page because I saw an event number higher than my plan's monthly event max and started to freak out.  After talking with @Niemyjski, it turns out the numbers on the org list page are for your entire retention period whereas I was assuming it was for the current billing period.

I would suggest adding a small italics blurb somewhere on the org page indicating that the numbers in the table above summarize the entire data retention period, which is xx.  That would have helped avoid any confusion.

**Comment by niemyjski** [comment]
We could add some text about entire retention period but I'm not sure about listing the retention period time frame as you could have more than one org.

**Comment by niemyjski** [comment]
Would you mind submitting a pull request for this. You'd need to update the app\organization\list.html file.

**Comment by BillHenning** [comment]
I'll let you add it since I don't know your CSS classes, etc.  Something along the lines of:
"The stack and event counts in the table above summarize the entire data retention period for each organization."

**Comment by ejsmith** [comment]
How about just adding Total to the headers?  Total Stacks, Total Events.

**Comment by niemyjski** [comment]
@BillHenning would that help?
