### ISSUE TITLE
Returning to paginated views after looking at event details returns you to page 1, not the page you came from

### ISSUE THREAD

**Issue by boydpatterson** [exceptionless/Exceptionless.UI#87]
Most views in the UI allow 20 items per page, and you get to cycle between pages.  A frequent use case for me is to look at all my sessions, and then drill into a session to see the events.  If I move beyond page 1 of my session events, drill into a session, and then press the browser back button to return to the list... I'm returned to page 1, not the page I was just on.  This makes drilling into details very cumbersome for any events not listed on the first page.

**Comment by caesay** [comment]
This would be closed by #133

**Comment by niemyjski** [comment]
closing in favor of #133
