### ISSUE TITLE
Keyboard Shortcuts Caching?

### ISSUE THREAD

**Issue by jmoeltjen** [exceptionless/Exceptionless.UI#92]
Keyboard Shortcuts seem to be caching last event/options on dashboards - allowing you to do CTRL + UP, etc, and that (I think) always being relative to the last event that you did it on.

On a dashboard, when I hit SHIFT + ? it brings up the default screen.

If I click into an event, it brings up the one allowing me to go to the stack, view the previous occurrence, etc.

If I do that, it works properly. Awesome.

But now if I go back to the dashboard, for example, SHIFT + ? brings up the same overlay telling me I can go to the stack, view the previous occurrence, etc.

If I do CTRL + UP there, it goes to the stack for the event I originally did it for when I was on the event occurrence page several pages before.

If I go into another event and use the same command, it seems to perform properly.

If I do a refresh, it goes back to just showing me the default overlay on the dashboards, etc.

See attached GIF.

![keyboard-shortcut-bug](https://cloud.githubusercontent.com/assets/6110870/14613220/0b28a77c-0561-11e6-8f09-849423d741fb.gif)

**Comment by niemyjski** [comment]
@jmoeltjen can you please let me know if this isn't fixed in the latest build (building and deploying shortly) version >= 2.5.913.
