### ISSUE TITLE
Tags don't line break when they don't fit.

### ISSUE THREAD

**Issue by gardebring** [exceptionless/Exceptionless.UI#96]
When you have Tags that fill more space than the width of the Overview, they will continue on to the right, breaking the design. Expected behaviour would be that they line-break down onto a new row.
To reproduce, simply produce a log with multiple tags and resize the window to a small size.

This issue occurs on Chrome on Windows 10 and Windows 7, have not tested other browsers.

**Comment by niemyjski** [comment]
Thanks for reporting this, we'll get it fixed.
